---
 
- name: cisco_check_mtu
  hosts: all
  connection: local
  gather_facts: no
 
  tasks:

    - name: "Gather Facts"
      ios_facts:
        gather_subset: all

    - name: "Find and check MTU"    
      vars:
       interface_port: "{{ interface_port }}"
       interface_values: "{{ ansible_net_interfaces[interface_port] }}"
      debug:
        msg: "OK"
      when:
        - interface_values.mtu == {{ expected_mtu }}
        
