---
 
- name: cisco_check_mtu
  hosts: all
  connection: local
  gather_facts: no
 
  tasks:

    - name: "Gather Facts"
      ios_facts:
        gather_subset: all

    - name: "Find MTU"    
      vars:
        mtu: ansible_facts[ansible_net_interfaces]["FastEthernet1/0/3"]
                              
    - name: "Check mtu"
      debug:
        msg: mtu 
