---
 
- name: cisco_check_mtu
  hosts: all
  connection: local
  gather_facts: no
 
  tasks:

    - name: "Gather Facts"
      ios_facts:
        gather_subset: all

    - name: "Find MTU"    
      vars:
       interface_port: "{{ interface_port }}"
       interface_values: "{{ ansible_net_interfaces[interface_port] }}"
      debug:
        var:  interface_values.mtu

