---
- name: cisco_remediation_ios
  hosts: all
  connection: local
  
  tasks:
 
    - name: make interface up
      ios_interface:
        name: "{{ interface_name }}"
        enabled: True
        state: up
      tags:
         - noshut
 
    - name: make interface down
      ios_interface:
        name: "{{ interface_name }}"
        enabled: False
        state: down
      tags:
        - shut
