---
- name: cisco_remediation_ios
  hosts: all
  
  tasks:
 
    - name: make interface up
      ios_interface:
        name: "{{ interface_name }}"
        enabled: True
      tags:
         - noshut
 
    - name: make interface down
      ios_interface:
        name: "{{ interface_name }}"
        enabled: False
      tags:
        - shut
