---
- name: cisco_remediation_ios
  hosts: all
  connection: local
  
  tasks:
 
#    - name: make interface up
#      ios_interface:
#        name: "{{ interface_name }}"
#        enabled: True
#        state: up
#      tags:
#         - noshut
 
 #   - name: make interface down
 #     ios_interface:
 #       name: "{{ interface_name }}"
 #       enabled: False
 #       state: down
 #     tags:
 #       - shut

    - name: use config to make interface down 
      ios_config:
        lines:
          - shutdown
        parents: interface {{ interface_name }}
      tags:
        - shut

    - name: use config to make interface up 
      ios_config:
        lines:
          - no shutdown
        parents: interface {{ interface_name }}
      tags:
        - noshut
